export const Nationalities = [
  { code: 'US', name_en: 'American', name_ar: 'أمريكي' },
  { code: 'EU', name_en: 'European', name_ar: 'أوروبي' },
  { code: 'JP', name_en: 'Japanese', name_ar: 'ياباني' },
  { code: 'GB', name_en: 'British', name_ar: 'بريطاني' },
  { code: 'AU', name_en: 'Australian', name_ar: 'أسترالي' },
  { code: 'CA', name_en: 'Canadian', name_ar: 'كندي' },
  { code: 'CH', name_en: 'Swiss', name_ar: 'سويسري' },
  { code: 'CN', name_en: 'Chinese', name_ar: 'صيني' },
  { code: 'EG', name_en: 'Egyptian', name_ar: 'مصري' },
  { code: 'SA', name_en: 'Saudi', name_ar: 'سعودي' },
  { code: 'AE', name_en: 'Emirati', name_ar: 'إماراتي' },
  { code: 'KW', name_en: 'Kuwaiti', name_ar: 'كويتي' },
  { code: 'IN', name_en: 'Indian', name_ar: 'هندي' },
  { code: 'PK', name_en: 'Pakistani', name_ar: 'باكستاني' },
  { code: 'BR', name_en: 'Brazilian', name_ar: 'برازيلي' },
  { code: 'RU', name_en: 'Russian', name_ar: 'روسي' },
  { code: 'ZA', name_en: 'South African', name_ar: 'جنوب أفريقي' },
  { code: 'NG', name_en: 'Nigerian', name_ar: 'نيجيري' },
  { code: 'TR', name_en: 'Turkish', name_ar: 'تركي' },
  { code: 'MX', name_en: 'Mexican', name_ar: 'مكسيكي' },
  { code: 'KR', name_en: 'South Korean', name_ar: 'كوري جنوبي' },
  { code: 'SE', name_en: 'Swedish', name_ar: 'سويدي' },
  { code: 'NO', name_en: 'Norwegian', name_ar: 'نرويجي' },
  { code: 'DK', name_en: 'Danish', name_ar: 'دنماركي' },
  { code: 'PL', name_en: 'Polish', name_ar: 'بولندي' },
  { code: 'AR', name_en: 'Argentine', name_ar: 'أرجنتيني' },
];
