export const TERMS_EN = `
  <h3>Introduction</h3>
  <p>Welcome to <span class="text-primary">ecommerce.tmg.com.eg</span> website. These terms and conditions apply to the Site, and all of its divisions, subsidiaries, and affiliate operated Internet sites which reference these Terms and Conditions. By accessing, registering data and creating an account on the Site, the Site user (“Client /Site User”) hereby acknowledges his acceptance of these Terms and Conditions. If the Client do not agree to these Terms and Conditions of use, he shall not use this website. The management of this Site reserves the right, to change, modify, add, or remove portions of these Terms and Conditions of use at any time. Changes will be effective when posted on the Site with no other notice provided to the client. Please check these Terms and Conditions of use regularly for updates. The Client continued use of the Site following the posting of changes to these Terms and Conditions of use constitutes full consent of the Client for those changes or amendments.</p>

  <h3>Terms and Conditions of Use</h3>

  <h3>Use of the Site</h3>
  <ul>
    <li>To visit, register data and activate the account on this site, the Site User must be at least 21 years old.</li>
    <li>The Client has the right to create and register for only one account on the Site.</li>
    <li>In the event that the Client created several accounts on the Site, the management of the site or Talaat Mostafa Group or affiliates companies, will have the right to take legal measures with this Client or cancel or close other accounts without any prior notice or warning to the Client.</li>
    <li>In the event of Client’s failure to comply with of these Terms and Conditions, the account will be deactivated immediately and prevented from making any application on the Site.</li>
    <li>The Client is granted a license, which is non-transferable or non-assignable to any third party, to use this Site under the specified Terms and Conditions. The purpose of this license lies in the customer’s desire to review and purchase any of the residential, administrative or commercial units or services provided by one of Talaat Mostafa Group companies on the site. It is prohibited to use the site for any commercial purposes or to use an account in the name of any third party, unless permitted in writing by one of Talaat Mostafa Group companies. Failure to comply with these Terms and Conditions will lead to immediate revocation of the license granted in this paragraph without any prior warning or notification to the Client.</li>
    <li>The content appearing on this Site is displayed for marketing purposes for residential, administrative or commercial units or services provided by Talaat Mustafa Group Companies. The explanations and information related to prices and privileges of the units which are expressed on this Site are due to Talaat Mustafa Group Companies. However, any reference to any comments or other opinions that does appear on this site or on any other sites on the international information network (the Internet) to an entity or other person belong to its publisher and does not reflect a an opinion for Talaat Mustafa Group Companies, or its officers, directors, employees and personnel.</li>
    <li>Certain services and related features that may be made available on the Site may require registration or subscription. By choosing to register or subscribe to any of these services or related features, the Client acknowledges and agrees to provide accurate and current information and undertakes to update the same immediately if any changes occur. It is the Site User’s responsibility -Sole responsibility - to maintain the username, passwords and other methods of correctly determining the account usage. The full responsibility lies on owner of the account in relation to all activities that occur using the user name, password or his account. In addition , the Client shall report for any unauthorized use of his user name, password or account. The Site or Talaat Mustafa Group Companies or its affiliates or its officers, directors, employees and personnel shall not be responsible or liable, directly or indirectly, in any way for any loss or damage of any kind incurred as a result of, or in connection with the Client’s failure to comply with this section.</li>
    <li>During the registration and creating an account process on the site, the Client agrees to receive promotional emails from the site. It is possible to cancel this option later and not receive any promotional emails by clicking on the link at the bottom of any promotional email.</li>
    <li>The Client shall comply with all the laws in force regulating trade via the Internet and in any way will be responsible for any loss that may be incurred by him or inflicted on Talaat Mustafa Group Companies or affiliates companies or its officers, directors, employees and personnel, directly or indirectly, morally or physically as a result of any illegal or use or delegated to use the account created on the site by the client or by any third party who obtained the user name and password or disclosed the username or password information.</li>
    <li>The Client acknowledges and agrees that Talaat Mostafa Group Companies or affiliates companies have an absolute right and discretion at any time to request any clarification or implement the questionnaires it deems necessary (directly or through third parties) and to demand the Client to disclose additional information or provide additional documents to prove the Client’s identity or financial tools .</li>
    <li>In the event that the applicant for the data registration represents a legal entity or company, then it must have the right to practice commercial activity in the Arab Republic of Egypt in accordance with the law and shall provide all the required information and documents that include commercial license, commercial registration form and documents that indicate the identity of the legal representative having the authorities.</li>
    <li>The Site, Talaat Mustafa Group Companies or affiliates companies or its officers, directors, employees and personnel, does not bear any claims arising from errors or negligence, whether it occurred from the Client or third parties or any financial losses or defamation of the reputation or any special damage arising from misuse or inability of the Client to use the site. the Client hereby acknowledges his acceptance to exempt the Site, its management or Talaat Mustafa Group Companies or affiliates companies or its officers, directors, employees and personnel from any responsibility regarding any claim or dispute or costs or damages and any direct or indirect loss to any party arising from the actions of the Client .The Client acknowledges, in particular, the waiver of any demands in this regards in accordance with the laws in force.</li>
    <li>The Client agrees that Talaat Mostafa Group Companies or affiliates companies have the right to contact the Client via e-mail or through the broadcast of promotional advertisements on the Site and the Client agrees that all agreements, advertisements, data and other communications that may be sent by one of the electronic means, specially e-mail messages, will replace their written counterparts in meeting Legal needs and procedures and shall be a burden of proof against the client.</li>
    <li>The Client acknowledges and agrees that by placing an order or making a payment through the Site, he shall be legally capable of entering into binding contracts, his credit/debit card or other payment method will be billed and charged. Also, the Client warrants that all the information provided for the purpose of processing payments is correct and he has the authorized and legal capacity to utilize the proffered payment method. The customer also acknowledges his agreement to the ability of Talaat Mostafa Group Companies shall be entitled to refuse or cancel any orders, whether confirmed or not, if their dues are not paid, in addition to the customer’s commitment to pay all compensation for the damage occurred.</li>
    <li>The Clients consents that website management (i) are entitled to record of telephone and video conversations between the sales, marketing and other relevant personnel of the parties in connection with this website or any potential transaction, (ii) don’t need to obtain any other necessary consent of, and give any necessary notice of such recordings  (iii) agrees, to the extent permitted by applicable law, that these recordings may be saved and submitted in any proceedings, if needed, in order to ensure the level of services.</li>
  </ul>

  <h3>User Submissions</h3>
  <p>Any participation submitted by the Client to the Site and/or provide to, including but not limited to, questions, reviews, comments, and suggestions (collectively, "Submissions") will become the sole and exclusive property of Talaat Mostafa Group Companies and shall not be returned to the Client. In addition to the rights applicable to any Submission, when the Client post comments or reviews to the Site, the Client also grant the site management and Talaat Mostafa Group Companies the right to use the name that the Client has submit, in connection with such review, comment, or other content. The Client shall not use a false e-mail address, pretend to be someone other than himself or otherwise mislead us or third parties as to the origin of any Submissions, which exposes the client to legal liability. The Site management shall have the right to, remove or edit any Submissions.</p>

  <h3>Order Acceptance and Pricing</h3>
  <p>Please note that there are cases the registration cannot be processed for various reasons. The Site management reserves the right to refuse or cancel any order for any reason at any given time. The Client may be asked to provide additional verifications or information, including but not limited to phone number and address, before we accept the order.</p>
  <p>The Site management are determined to provide the most accurate pricing information on the Site to our users; however, errors may still occur, such as cases when the price of an Unit is not displayed correctly on the website. As such, The Site management reserve the right to refuse or cancel any order. In the event that an item is mispriced, The Talaat Mostafa Group Companies may, at sole discretion, either contact the Client for instructions or cancel the order and notify you of such cancellation. We shall have the right to refuse or cancel any such orders whether or not the order has been confirmed.</p>

  <h3>Intellectual Property Rights</h3>
  <p>All intellectual property rights, whether registered or unregistered, in the Site, information content on the Site and all the website design, including, but not limited to, text, graphics, software, photos, video, music, sound, and their selection and arrangement, and all software compilations, underlying source code and software shall remain the sole property of Talaat Mostafa Group Companies. The entire contents of the Site also are protected by copyright as a collective work under Egyptian Intellectual Property laws and international conventions. Any violation against the intellectual property rights that is exclusively owned by Talaat Mostafa Group of Companies and published on this site constitutes an infringement that requires legal liability and compensation for damages.</p>

  <h3>Data Protection</h3>
  <p>Any personal information collected in relation to the use of this website will be held and used in accordant with our Privacy Policy, which is available on our Site. The client acknowledges and agrees that Talaat Mostafa Group Companies or affiliate companies are absolutely entitled to use the Client's data for the purpose of inquiry and verify the identity, which includes, but is not limited to, "taking credit inquiry actions, ....... etc."</p>

  <h3>Applicable law and dispute resolution</h3>
  <p>These terms and conditions are interpreted and applied according to the laws in force in the Arab Republic of Egypt. Accordingly, The client agrees that the jurisdiction will be hold to the Economic Courts.</p>

  <h3>Termination</h3>
  <p>In addition to any other legal or equitable remedies, The Site management and Talaat Mostafa Group Companies may, without prior notice to you, immediately terminate these Terms and Conditions or revoke any or all of your rights granted under the Terms and Conditions. Upon any termination of this Agreement, the Client shall immediately cease all access to and use of the Site and we shall, in addition to any other legal or equitable remedies, immediately revoke all password(s) and account identification issued to you and deny your access to and use of this Site in whole or in part. Any termination of this agreement shall not affect the respective rights and obligations (including without limitation, payment obligations) of the parties arising before the date of termination. The Client furthermore agree that the Site shall not be liable to the Client or to any other person as a result of any such suspension or termination. If the Client is dissatisfied with the Site or with any terms, conditions, rules, policies, guidelines, or practices in operating the Site, the sole and exclusive remedy for the Site User is to discontinue using the Site.</p>

  <div><p class="inline">N.B.</p> <p class="underline"> An English language translation have been prepared, however, in the event of a conflict between the Arabic version and the English version, the Arabic text shall prevail.</p></div>
`;
